### ISSUE TITLE
Unable to create lockinamp_device and other custom extensions. 

### ISSUE THREAD

**Issue by Saksham20** [ben-dichter-consulting/ndx-tempo#3]
@bendichter  @luiztauffer 
I am unable to have a custom `lockinamp_device` (extension of DynamicTable) be successfully written to an nwb file. The **lockinamp_device** is created successfully and attached to the open nwbfile. But when I write it and then reopen it, its gone. 
I think the `io.write()` operation of `NWBHDF5IO` is not recognizing the class and the attribute structure. PRobably I am not creating the `lockinamp_device` class the right way. I am not using `get_class` but creating it like [here](https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim/src/pynwb/ndx_tempo/tempo.py#L20). its schema is [here](https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim/spec/ndx-tempo.extensions.yaml#L102)

 ```
with NWBHDF5IO('test_ndx-tempo.nwb', 'w') as io:
    io.write(nwbfile) 
nwbfile.processing['device_cont']['mylockinamp'].demod_bandwidth.data 
```
Out:
``` 
[150]
```
Snippet above is from [here](https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim/src/pynwb/tests/mytest.py#L73) and below is from [here](https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim/src/pynwb/tests/mytest.py#L76)
```
with NWBHDF5IO('test_ndx-tempo.nwb', 'r') as io:
    nwbfile2 = io.read()
nwbfile.processing['device_cont']['mylockinamp'].demod_bandwidth.data 
```
Out:
```
'LockInAmplifierDevices' object has no attribute 'demod_bandwidth'
```

Can you try running this code, [here](https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim/src/pynwb/tests/mytest.py) again and see what error/warning you get? 

There is a warning when I try to run it:
The warning is : 
```
C:\Users\Saksham\Anaconda3\lib\site-packages\hdmf\build\objectmapper.py:780: OrphanContainerWarning: 'None' (Measurement) for 'mylockinamp' (LockInAmplifier)
  warnings.warn(msg, OrphanContainerWarning)
C:\Users\Saksham\Anaconda3\lib\site-packages\hdmf\backends\hdf5\h5tools.py:428: BrokenLinkWarning: /analysis\mylockinamp
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
C:\Users\Saksham\Anaconda3\lib\site-packages\hdmf\backends\hdf5\h5tools.py:428: BrokenLinkWarning: /processing/device_cont\mylockinamp
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
```

**Comment by bendichter** [comment]
Is the data present in the HDF5 file, if you use h5py or HDFView?

**Comment by Saksham20** [comment]
> Is the data present in the HDF5 file, if you use h5py or HDFView?

No, the data is absent when I try to view using HDFview, I get a question mark beside the datatypes. 
You can run [this](https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim/src/pynwb/tests/mytest.py) code and open with HDFview

**Comment by bendichter** [comment]
Running your code with the latest, I get an error on write:

```python
/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py:780: OrphanContainerWarning: 'None' (Measurement) for 'mylockinamp' (LockInAmplifier)
  warnings.warn(msg, OrphanContainerWarning)
Traceback (most recent call last):
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 586, in build
    bldr_data, dtype = self.convert_dtype(spec, container.data)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 179, in convert_dtype
    tmp, tmp_dtype = cls.convert_dtype(spec, elem)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 193, in convert_dtype
    dtype_func = cls.__resolve_dtype(type(value), spec_dtype)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 137, in __resolve_dtype
    raise ValueError(msg)
ValueError: expected float32, received int64 - must supply float32 or higher precision
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-d031a9f86981>", line 2, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py", line 269, in write
    call_docval_func(super().write, kwargs)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 343, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/backends/io.py", line 43, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py", line 156, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py", line 743, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 539, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 756, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 772, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 821, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 783, in __add_containers
    rendered_obj = build_manager.build(value, source=source, spec_ext=spec)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py", line 156, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py", line 743, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 538, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 732, in __add_datasets
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 783, in __add_containers
    rendered_obj = build_manager.build(value, source=source, spec_ext=spec)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py", line 156, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/manager.py", line 743, in build
    builder = obj_mapper.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/Users/bendichter/anaconda3/lib/python3.7/site-packages/hdmf/build/objectmapper.py", line 589, in build
    raise Exception(msg) from ex
Exception: could not resolve dtype for Measurement 'None'
```

**Comment by bendichter** [comment]
this line:

```
ValueError: expected float32, received int64 - must supply float32 or higher precision
```
suggests you are using the wrong datatype somewhere

**Comment by bendichter** [comment]
Also, there is some funky path manipulation stuff in mytest.py. Any reason you can't use `pip install -e .`? Then you can use `from ndx_tempo import *` (though I don't really like the wildcard import. Doing it from a single library is permissible I suppose)

**Comment by Saksham20** [comment]
can you run this file: https://github.com/ben-dichter-consulting/ndx-tempo/blob/trim_test/src/pynwb/tests/mytest.py
also install that using `pip install -e .`
I have removed the 'Measurement' datatype . I get the error 
```
C:\Users\Saksham\Anaconda3\lib\site-packages\hdmf\backends\hdf5\h5tools.py:428: BrokenLinkWarning: /analysis\mylockinamp
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
C:\Users\Saksham\Anaconda3\lib\site-packages\hdmf\backends\hdf5\h5tools.py:428: BrokenLinkWarning: /processing/device_cont\mylockinamp
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
```
I wonder if its the forward and backslash in the link that is causing the problem
